server:
  port: 8100

spring:
  application:
    name: item-service
  data:
    mongodb:
      uri: mongodb+srv://admin:zlwOj8Aqje5NxifT@cluster0.kdvjrko.mongodb.net/cluster0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
