server:
  port: 8300

spring:
  application:
    name: email-service
  data:
    mongodb:
      uri: mongodb+srv://admin:zlwOj8Aqje5NxifT@cluster0.kdvjrko.mongodb.net/cluster0
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  queue:
    name:
      email: email_queue
